const projects = [
  { no: "01", type: "PERSONALITY · DIGITAL EXPERIENCE", title: "日主人格图鉴", desc: "把八字日主转译成一套面向 Z 世代的东方人格 IP。用角色、色彩和微妙的性格文案，让传统概念变得可见、可认领、可分享。", tags: ["Creative direction", "Product design", "AI-assisted"], tone: "jade", glyph: "十" },
  { no: "02", type: "MUSIC · IN PROGRESS", title: "Songs from the margins", desc: "关于暗恋、离开和那些没有被说出口的瞬间。写歌、编曲，也在学习如何把私人情绪变成别人能进入的故事。", tags: ["Songwriting", "Ableton Live", "Narrative pop"], tone: "rose", glyph: "♪" },
  { no: "03", type: "INTERACTIVE STORY · CONCEPT", title: "南屿心动", desc: "一部关于靠近、误读与选择的互动叙事作品。用现实感人物和细小的情绪分支，探索关系里那些难以命名的时刻。", tags: ["World building", "Writing", "Visual direction"], tone: "blue", glyph: "雨" },
];

export default function Home() {
  return <main className="site-shell">
    <nav className="nav"><a className="mark" href="#top">HC<span>●</span></a><div className="nav-links"><a href="#work">Selected work</a><a href="#about">About</a><a href="#contact">Contact</a></div><span className="nav-status"><i /> Available for select projects</span></nav>
    <section className="hero" id="top"><div className="hero-kicker"><span>01 — 2026</span><span>Creative technologist / songwriter</span></div><div className="hero-title"><h1>Making<br /><em>feelings</em><br />visible.</h1><div className="hero-note"><p>I’m Henry — a business student, creative maker, and storyteller interested in the space between culture and technology.</p><a href="#work" className="round-arrow" aria-label="Scroll to selected work">↘</a></div></div><div className="hero-orbit"><div className="orbit-core">好<br /><small>奇</small></div><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><span className="orbit-label label-a">curiosity</span><span className="orbit-label label-b">emotion</span><span className="orbit-label label-c">form</span></div></section>
    <section className="intro" id="about"><p className="section-label">02 — A point of view</p><div><h2>I like ideas that feel<br /><span>personal at first</span><br />and universal later.</h2><p className="intro-copy">My work moves between brand thinking, interactive experiences and music. I’m drawn to projects that turn something abstract — a personality, a memory, a feeling — into something people can see themselves in.</p></div></section>
    <section className="work" id="work"><div className="section-head"><p className="section-label">03 — Selected work</p><span>2024 — now</span></div><div className="project-list">{projects.map((p) => <article className="project" key={p.no}><div className={`project-art ${p.tone}`}><span className="art-no">{p.no}</span><span className="art-glyph">{p.glyph}</span><span className="art-caption">{p.type}</span></div><div className="project-info"><p className="project-type">{p.type}</p><h3>{p.title}</h3><p className="project-desc">{p.desc}</p><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div><a className="project-link" href="#contact">View project <b>↗</b></a></div></article>)}</div></section>
    <section className="manifesto"><div className="manifesto-symbol">✳</div><p>“The best work leaves a little room<br />for the viewer to bring themselves in.”</p></section>
    <section className="contact" id="contact"><p className="section-label">04 — Say hello</p><div className="contact-row"><h2>Have something<br /><em>in mind?</em></h2><div><p>I’m always interested in thoughtful collaborations, strange ideas, and conversations that turn into something real.</p><a className="email" href="mailto:hello@henrychen.studio">hello@henrychen.studio <span>↗</span></a></div></div></section>
    <footer><span>© 2026 Henry Chen</span><span>Built with curiosity</span><span>Shenzhen / Hong Kong / online</span></footer>
  </main>;
}
