const projects = [
  { no: "01", type: "PERSONALITY · DIGITAL EXPERIENCE", title: "日主人格图鉴", desc: "把八字日主转译成一套面向 Z 世代的东方人格 IP。用角色、色彩和微妙的性格文案，让传统概念变得可见、可认领、可分享。", tags: ["Creative direction", "Product design", "AI-assisted"], tone: "jade", image: "/projects/daymaster-cover.png", href: "https://day-self-personality.henrychen-88.chatgpt.site" },
  { no: "02", type: "BRAND · INTEGRATED CAMPAIGN", title: "乐堡冻冻酒", desc: "围绕“别抖了，来抖乐堡”的核心概念，完成从洞察、创意到社交内容的整合营销方案。", tags: ["Campaign strategy", "Creative", "Social content"], tone: "rose", image: "/projects/leb-cover.png", href: "/projects/leb-marketing.pdf" },
  { no: "03", type: "PERSONAL · PRESENTATION", title: "律动摇摆", desc: "一份关于我、音乐与身体的个人介绍。把自我表达放进轻松、跳跃的视觉语言里。", tags: ["Personal branding", "Presentation", "Visual storytelling"], tone: "blue", image: "/projects/rhythm-cover.png", href: "/projects/rhythm-swing.pdf" },
  { no: "04", type: "BRAND · CAMPAIGN PROPOSAL", title: "蜜雪冰城", desc: "从品牌语境与年轻消费场景出发，完成一份蜜雪冰城相关的营销提案。", tags: ["Brand strategy", "Consumer insight", "Campaign"], tone: "yellow", image: "/projects/mixue-cover.jpeg", href: "/projects/mixue-plan.pptx" },
  { no: "05", type: "AI · WEB APPLICATION", title: "商品竞品分析 Agent", desc: "一个支持多 Agent 协作的商品竞品分析工作台，把搜索、抓取、分析与写作串成一条可追踪的工作流。", tags: ["AI product", "Web app", "Agent workflow"], tone: "violet", image: null, href: "/projects/competitor-agent.zip" },
];

export default function Home() {
  return <main className="site-shell">
    <nav className="nav"><a className="mark" href="#top">HC<span>●</span></a><div className="nav-links"><a href="#work">Selected work</a><a href="#about">About</a><a href="#contact">Contact</a></div><span className="nav-status"><i /> Available for select projects</span></nav>
    <section className="hero" id="top"><div className="hero-kicker"><span>01 — 2026</span><span>Creative technologist / songwriter</span></div><div className="hero-title"><h1>Making<br /><em>feelings</em><br />visible.</h1><div className="hero-note"><p>I’m Henry — a business student, creative maker, and storyteller interested in the space between culture and technology.</p><a href="#work" className="round-arrow" aria-label="Scroll to selected work">↘</a></div></div><div className="hero-orbit"><div className="orbit-core">好<br /><small>奇</small></div><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><span className="orbit-label label-a">curiosity</span><span className="orbit-label label-b">emotion</span><span className="orbit-label label-c">form</span></div></section>
    <section className="intro" id="about"><p className="section-label">02 — A point of view</p><div><h2>I like ideas that feel<br /><span>personal at first</span><br />and universal later.</h2><p className="intro-copy">My work moves between brand thinking, interactive experiences and music. I’m drawn to projects that turn something abstract — a personality, a memory, a feeling — into something people can see themselves in.</p></div></section>
    <section className="work" id="work"><div className="section-head"><p className="section-label">03 — Selected work</p><span>2024 — now</span></div><div className="project-list">{projects.map((p) => <article className="project" key={p.no}><a className={`project-art ${p.tone}`} href={p.href} target="_blank" rel="noreferrer"><span className="art-no">{p.no}</span>{p.image ? <img src={p.image} alt="" /> : <span className="art-glyph">AI</span>}<span className="art-caption">{p.type}</span></a><div className="project-info"><p className="project-type">{p.type}</p><h3>{p.title}</h3><p className="project-desc">{p.desc}</p><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div><a className="project-link" href={p.href} target="_blank" rel="noreferrer">Open project <b>↗</b></a></div></article>)}</div></section>
    <section className="manifesto"><div className="manifesto-symbol">✳</div><p>“The best work leaves a little room<br />for the viewer to bring themselves in.”</p></section>
    <section className="contact" id="contact"><p className="section-label">04 — Say hello</p><div className="contact-row"><h2>Have something<br /><em>in mind?</em></h2><div><p>I’m always interested in thoughtful collaborations, strange ideas, and conversations that turn into something real.</p><a className="email" href="mailto:hello@henrychen.studio">hello@henrychen.studio <span>↗</span></a></div></div></section>
    <footer><span>© 2026 Henry Chen</span><span>Built with curiosity</span><span>Shenzhen / Hong Kong / online</span></footer>
  </main>;
}
